### ISSUE TITLE
Adding vmin and vmax to gplt.choropleth

### ISSUE THREAD

**Issue by redfrexx** [ResidentMario/geoplot#163]
Hi, 

I've just started using geoplot and I wanted to plot several maps in one figure with one shared colorscale. When I plot the maps individually in the figure the value ranges of the colorscales differ depending on the data and then the maps are not well comparable. How do you feel about adding a vmin and vmax parameters to gplt.choropleth to control the value range of the colorscale of each map? In this way one could make sure that all maps use the same colorscale. I experimented a bit with the code yesterday and it seems like it only takes a small change in geoplot.py.

https://github.com/redfrexx/geoplot/blob/2bf00a289938821b57ef8c88dc7667a0278592bc/geoplot/geoplot.py#L68-L69

Or is there another way of plotting several maps in one figure with just one shared colorscale?

**Comment by ResidentMario** [comment]
Thanks for submitting this issue! Looks like there's a bit of work that needs to be done here to support this feature request.

`geoplot` actually did use to have `vmin` and `vmax` parameters for all of the plot types that supported a colormap. This feature was removed in the [`0.3.0` release](https://github.com/ResidentMario/geoplot/releases/tag/0.3.0) in order to reduce the top-level complexity of the API. `vmin` and `vmax` were not great top-level parameters because:
* Colorbar manipulation is an advanced use-case.
* `vmin` and `vmax` are defined parameters in a small handful of the plot types in `matplotlib`&mdash;mainly `imshow` and `contour`. Most other plot types in `matplotlib` have you normalize the colormap yourself, and pass the resulting RGBA values directly to the plot. For example, here is the answer provided for [this question on StackOverflow](https://stackoverflow.com/questions/43442925/color-coding-using-scalar-mappable-in-matplotlib):

```python
cmap= plt.cm.bone_r
# create normalization instance
norm = matplotlib.colors.Normalize(vmin=0, vmax=1000) 
# create a scalarmappable from the colormap
sm = matplotlib.cm.ScalarMappable(cmap=cmap, norm=norm)    
sm.set_array([])  
barHeight = 3
ticklist = []
def drawLoadDuration(period, starty, voltage):
    ax3.broken_barh((period), (starty, barHeight), alpha=1, 
                    facecolors=cmap(norm(voltage)), lw=0.5, zorder=2)
```

This hints at the correct way to normalize your colormap in `geoplot`, which would be using the following recipe:

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import geoplot as gplt

norm = mpl.colors.Normalize(vmin=1, vmax=5)
cmap = mpl.cm.ScalarMappable(norm=norm, cmap='viridis').cmap

fig, axarr = plt.subplots(1, 2, figsize=(16, 6))

gplt.pointplot(
    injurious_collisions[injurious_collisions['NUMBER OF PERSONS INJURED'] <= 5],
    hue='NUMBER OF PERSONS INJURED',
    legend=True,
    cmap=lambda v: cmap(norm(v)),
    ax=axarr[0]
)

gplt.pointplot(
    injurious_collisions[injurious_collisions['NUMBER OF PERSONS INJURED'] >= 3],
    hue='NUMBER OF PERSONS INJURED',
    legend=True,
    cmap=lambda v: cmap(norm(v)),
    ax=axarr[1]
)
```

Unforunately `cmap` currently only supports input in the form of a [`matplotlib.colors.Colormap` instance](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.colors.Colormap.html#matplotlib.colors.Colormap) or a predefined string name for such a colormap. `geoplot` does not currently support passing a custom function such as this. I will backlog adding this feature to the API.

So the TLDR is that no, this isn't possible yet, but will be "soon"™️.

**Comment by redfrexx** [comment]
Thank you very much for your answer! I'll stick to this solution then for now.

**Comment by story645** [comment]
Any chance you'd consider letting the user pass in a norm object and under the hood do `lambda v: cmap(norm(v))` mostly because I think `cmap=cmap, norm=norm` is a common enough usage pattern that users would expect it (I did), whereas honestly `lambda v: cmap(norm(v))` is a bit harder to explain (and frankly not even intuitive to me).

**Comment by ResidentMario** [comment]
I like the idea of having a `norm` parameter, yeah. That covers all of the colormap uses cases. Perhaps both the ability to pass a function and the `norm` should be added.

**Comment by ResidentMario** [comment]
Colormap normalization has now been added to `geoplot` as of #168.

The changeset that I pushed was ultimately very small, but I experimented with and ultimately abandoned a couple of more advanced and technically intricate changes that I ultimately abandoned, but nevertheless want to document here for posterity:

* Allowing an arbitrary function as input to `norm`.

   This turned out to not work so well because it prevented the use of a legend (e.g. setting `legend=True`) when a continuous colormap is used (e.g. `k=None`). That's because a function is a discrete representation of a color scale, whereas the `colorbar` used for the legend when the colormap is continuous requires a continuous representation. `matplotlib` would barf.

   The combination of [colorbar manipulation](https://matplotlib.org/3.1.1/tutorials/colors/colormap-manipulation.html) and [colormap normalization](https://matplotlib.org/3.1.1/tutorials/colors/colormapnorms.html) should cover most of the use cases, although it may be a bit heavy-handed code-wise.

* Allowing an arbitrary function as input to `cmap`.

   This this has the same colorbar-breaking problem as abritrary norms. This also breaks convention with the `matplotlib` API, which has a different way of specifying custom colors (see the next bullet point).

* Allowing a list of colors as input to `color`.

   Many `matplotlib` plotters allow you to specify custom colors per feature by passing a list or iterable to the `color` parameter. This does not work in `geoplot`: currently you can only set a single static color (e.g. `steelblue` or `(0.5, 0.5, 0.5, 0.5)`) via the `color` parameter.

   `color` is in many cases not specific enough, however, and has overlapping jurisdiction with much better defined variables like `facecolor` and `edgecolor`. `geoplot` supports `color` as best it can, but prefers the latter two both in the implementation and in the documentation. 

   However neither `facecolor` nor `edgecolor` is a plot property; these are instead individual properties of the plot markers (e.g. `descartes.Polygon` or `descartes.Point` objects), and don't make sense as listlike inputs, and are not typically specified as listlike inputs, so the user wouldn't expect to be able to specify them as such. It would also be surprising if these properties could be specified as lists whilst other keyword properties passed to the markers could not could not...

   All in all this would create a lot of code complexity for a very small and not very discoverable feature benefit.

**Comment by ResidentMario** [comment]
@redfrexx [Assuming you are OK with installing from master 😛] you can now do what you wanted to do by using the `norm` parameter:

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import geoplot as gplt

norm = mpl.colors.Normalize(vmin=1, vmax=5)
cmap = mpl.cm.ScalarMappable(norm=norm, cmap='viridis').cmap

fig, axarr = plt.subplots(1, 2, figsize=(16, 6))

gplt.pointplot(
    injurious_collisions[injurious_collisions['NUMBER OF PERSONS INJURED'] <= 5],
    hue='NUMBER OF PERSONS INJURED',
    legend=True,
    cmap=cmap,
    norm=norm,
    ax=axarr[0]
)

gplt.pointplot(
    injurious_collisions[injurious_collisions['NUMBER OF PERSONS INJURED'] >= 3],
    hue='NUMBER OF PERSONS INJURED',
    legend=True,
    cmap=cmap,
    norm=norm,
    ax=axarr[1]
)
```

One thing to be careful about: normalization will be applied to the colormap *after* quantization is applied to it. So if you are using a categorical colormap, e.g. `k != None`, your normalization should expect input in the form 0...N, where N is the number of categories your data has been bucketed into (presumably, `N == k`). Depending on your needs, you may want to use a continuous colormap (e.g. set `k=None`) to avoid this road bump entirely.

**Comment by ResidentMario** [comment]
@story645 The `norm` parameter is now implemented. Thanks for your help in thinking this feature through!
