### ISSUE TITLE
Colormap for kdeplot doesn't work without polyplot first

### ISSUE THREAD

**Issue by khof312** [ResidentMario/geoplot#176]
The following from the demo code makes a red heatmap:
```
ax = gplt.polyplot(boroughs, projection=gcrs.AlbersEqualArea())
gplt.kdeplot(collisions, cmap='Reds', shade=True, clip=boroughs, ax=ax)
```

But if I *just* try `kdeplot`, I get a blue colormap:
```
ax = gplt.kdeplot(collisions, cmap='Reds', shade=True, clip=boroughs)
```
Any ideas what's going wrong? I am using Geoplot v0.3.1, Geopandas v0.4.1, on Windows 7 Pro. If you can't replicate let me know and I can attach some images. Thanks!!!

**Comment by ResidentMario** [comment]
Hi @khof312. Want to first clarify what you mean with that second code snippet. Do you mean that when you run the following:

```python
gplt.kdeplot(collisions, cmap='Reds', shade=True, clip=boroughs, projection=gcrs.AlbersEqualArea())
```

You get a KDEPlot with a blue colormap instead of a red one? Or is it:

```python
ax = gplt.kdeplot(collisions, cmap='Reds', shade=True, clip=boroughs)
gplt.polyplot(boroughs, ax=ax)
```

**Comment by ResidentMario** [comment]
OK, I can reproduce this locally. It looks like the `cmap` variable is not being propagated correctly.

**Comment by khof312** [comment]
Yeah, sorry -- it's the first one. I supply 'Reds' but I get 'Blues. Thanks for your help :)

**Comment by ResidentMario** [comment]
Hi, so it turns out that this parameter was not being properly propagated to the underlying `kdeplot` when `projection=None`, causing the colormap used to always be whatever `sns.kdeplot` is set to use by default on your system.

I've minted a new release, `0.3.2` which fixes this bug as well as a few others, and adds a test suite which will catch issues such as this one in the future. You can get the updated version of the package with this fix via `pip` with `pip install -U geoplot`; if you are using `conda`, it'll be available there via `conda install -U geoplot` probably by the end of the day.

Thanks for reporting this issue! For smaller questions in the future you should also check out [the geoplot gitter room](https://gitter.im/geoplot/community).
