### ISSUE TITLE
can't plot data under projected coordinate system

### ISSUE THREAD

**Issue by CNFeffery** [ResidentMario/geoplot#208]
I found `geoplot` can't plot data under projected coordinate system:

![image](https://user-images.githubusercontent.com/49147660/77228713-177c3700-6bc4-11ea-8c67-51b463a4bad0.png)
```Python
boston_zip_codes = gpd.read_file('geometry/boston-zip-codes.geojson')

ax = gplt.polyplot(boston_zip_codes, 
                   facecolor='white', 
                   edgecolor='lightgrey', 
                   linewidth=0.5)
```
```Python
ax = gplt.polyplot(boston_zip_codes.to_crs('EPSG:32619'), 
                   facecolor='white', 
                   edgecolor='lightgrey', 
                   linewidth=0.5)
```
use the data from `geoplot-data`.

**Comment by ResidentMario** [comment]
Yes, `geoplot` only supports data in lat-long coordinate format. Before you create a plot, you will first have to change your data to use the lat-long CRS (`epsg:4326` I believe).

This is implicitly referenced in [the part of the user guide covering coordinate reference systems](https://residentmario.github.io/geoplot/user_guide/Working_with_Geospatial_Data.html#coordinate-reference-systems), leaving this ish open because I think I should make this clearer.

**Comment by CNFeffery** [comment]
> Yes, `geoplot` only supports data in lat-long coordinate format. Before you create a plot, you will first have to change your data to use the lat-long CRS (`epsg:4326` I believe).
> 
> This is implicitly referenced in [the part of the user guide covering coordinate reference systems](https://residentmario.github.io/geoplot/user_guide/Working_with_Geospatial_Data.html#coordinate-reference-systems), leaving this ish open because I think I should make this clearer.

thanks a lot!
