### ISSUE TITLE
Adding legend title in .pointplot()

### ISSUE THREAD

**Issue by joelm67** [ResidentMario/geoplot#211]
I am trying to add a legend title to a graph I made using geoplot.pointplot() and can't finda way to do it in the function or by calling .legend() afterwards. Is there a workaround that I am missing or is would it be possible to add an argument legend_title that would allow a legend title to be added? 

I am trying to make a graph showing the wind speed at various locations of hurricane Florence and would like to title my legend "Wind Speed (MPH)" Here is the code I am using to graph the hurricane:
```
fig,ax = plt.subplots(1, figsize=(20,20))
base = country[country['NAME'].isin(['Alaska','Hawaii']) == False].plot(ax=ax, color='#3B3C6E')
scheme = mc.Quantiles(florence['Wind'], k=5)
gplt.pointplot(florence, hue='Wind', cmap='cool',legend = True, scheme = scheme, ax=ax);
ax.axis('off')
ax.set_title("Hurricane Florence in US Map", fontsize=25);
```

Here is the output:

![Hurricane](https://user-images.githubusercontent.com/45672453/78505801-73ee6300-773b-11ea-8e5f-e4cb124e52c8.png)

**Comment by ResidentMario** [comment]
Somewhat tangential but I'm pretty sure `.legend()` is a no-op in this case because all of the patches on the screen are drawn using geometry primitives. `.legend()` only works for higher-level plotting methods, e.g. `ax.scatter`. You'd want to use the `.get_legend()` method, but since `matplotlib` doesn't seem to support modifying the legend after drawing it, this won't help you either.

Anyway to answer your question.

`geoplot` supports a `legend_kwargs` param that lets you pass keyword arguments directly to the `ax.legend` method. So getting what you want is as easy as:

```python
fig,ax = plt.subplots(1, figsize=(20,20))
base = country[country['NAME'].isin(['Alaska','Hawaii']) == False].plot(ax=ax, color='#3B3C6E')
scheme = mc.Quantiles(florence['Wind'], k=5)
gplt.pointplot(florence, hue='Wind', cmap='cool',legend = True, legend_kwargs={'title': 'Foo Bar'}, scheme = scheme, ax=ax);
ax.axis('off')
ax.set_title("Hurricane Florence in US Map", fontsize=25);
```

This is discussed in the documentation in both the [user guide](https://residentmario.github.io/geoplot/user_guide/Customizing_Plots.html#legend) and in the [API reference](https://residentmario.github.io/geoplot/api_reference.html#geoplot.geoplot.pointplot).

**Comment by joelm67** [comment]
Thanks for the help worked like a charm!
