### ISSUE TITLE
Unable to install geoplot with pipenv under Ubuntu 20.04LTS 

### ISSUE THREAD

**Issue by kaufmanno** [ResidentMario/geoplot#264]
Hi, 

I am trying to install geoplot with pipenv under Ubuntu 20.04LTS. I get an error saying that Proj version 6.3.1 is installed, but cartopy requires at least version 8.0.0.

It seems to be related to issue [#1879 of cartopy](https://github.com/SciTools/cartopy/issues/1879).

What would be the latest version of geoplot installable with pip (or pipenv) without having to install Proj8.0.0 from source on Ubuntu 18.04 LTS or 20.04 LTS?

Cheers

**Comment by ResidentMario** [comment]
`geoplot` makes no guarantee of that it can be installed using `pip`, only `conda`&mdash'see further [Installation](https://residentmario.github.io/geoplot/installation.html) in the docs.

Anyway, `geoplot` don't pin a specific `cartopy` version in its `setup.py` at this time. Since the dependency issue you are referring to is related to the `0.20.0` release, I would simply `pip install cartopy==0.19.x` (or do the equivalent with `conda`). You should then be able to install any version of `geoplot`.
