### ISSUE TITLE
Assigning projections to plt.subplots()-generated axes generates rotated images

### ISSUE THREAD

**Issue by hinnefe2** [ResidentMario/geoplot#30]
First off, this is a great library, thanks for making it!

I'm running into some non-intuitive behavior when using projections with `plt.subplots()`-generated axes. Briefly, passing a `projection` argument to both `plt.subplots` (via `subplot_kw=`) and `gplt.polyplot` generates images which are rotated by ~30 degrees. Minimum working example below:

```
import geoplot as gplt
import geopandas as gpd
import shapely
import matplotlib.pyplot as plt

square = shapely.geometry.Polygon([(41.5, 88), (41.75, 88), (41.75, 87.5), (41.5, 87.5)])

fig, ax = plt.subplots(1,1, subplot_kw={'projection': gplt.crs.AlbersEqualArea()})

gplt.polyplot(gpd.GeoDataFrame({'geometry':square}, index=[1]), projection=gplt.crs.AlbersEqualArea(), ax=ax)
```

For me this generates a plot of a rectangle rotated by about 30 degrees.

Some notes:
1. Passing the projection argument to `plt.subplots` is mandatory because without it you get back a `matplotlib.axes._subplots.AxesSubplot` instead of a `cartopy.mpl.geoaxes.GeoAxesSubplot`
2. Omitting the projection argument in the `gplt.polyplot` call generates an image that is way too big and extends past the edge of the plot.

Versions:
```
geoplot==0.0.3
geopandas==0.2.1
Shapely==1.5.17.post1
matplotlib==2.0.0
Cartopy==0.15.1
```

**Comment by ResidentMario** [comment]
When you assign a projection to the figure at large, `geoplot` has no way of knowing where your "region of interest" will be once you start adding subplots. So you end up with...something.

If you calculate and pass the centroid as projection parameters:

```python
square = shapely.geometry.Polygon([(41.5, 88), (41.75, 88), (41.75, 87.5), (41.5, 87.5)])
fig, ax = plt.subplots(1,1, subplot_kw={'projection': gplt.crs.AlbersEqualArea(central_latitude=87.75,
                                                                               central_longitude=41.625)})

gplt.polyplot(gpd.GeoDataFrame({'geometry':square}, index=[1]), projection=gplt.crs.AlbersEqualArea(), ax=ax)
```

You get what you're looking for:

![image](https://cloud.githubusercontent.com/assets/3466341/25493026/d83e0100-2b42-11e7-8742-519245d264e1.png)

The [examples](http://www.residentmar.io/geoplot/gallery.html) always hardcode the projection centroid for this reason.

**Comment by hinnefe2** [comment]
Ah, I see. Thanks for sorting me out!

**Comment by ResidentMario** [comment]
For future reference for anyone coming across this issue that stumbles across the GH issue: `geoplot` automatically determines the central latitude and/or central longitude of the projection you are using by taking the midpoint of the `geopandas.GeoDataFrame.total_bounds` of your input data.

When you pass a projection to `matplotlib` instead via `plt.subplots`, `geoplot` doesn't get to perform this intermediate step because the value is being set someplace else. You have to manually input the central coordinates for the projection yourself. For example:

```python
proj = gcrs.AlbersEqualArea(central_longitude=-98, central_latitude=39.5)
f, axarr = plt.subplots(1, 2, figsize=(12, 4), subplot_kw={
    'projection': proj
})
gplt.polyplot(contiguous_usa, projection=proj, ax=axarr[0])
gplt.polyplot(contiguous_usa, projection=proj, ax=axarr[1])
```

This is discussed in the documentation: [Working with Projections#Projections on Subplots](https://residentmario.github.io/geoplot/user_guide/Working_with_Projections.html#projections-on-subplots).
