### ISSUE TITLE
Attempting to select Mollweide projection results in KeyError

### ISSUE THREAD

**Issue by urschrei** [ResidentMario/geoplot#36]
Using `0.0.3`, Matplotlib `2.0.2`, Latest Jupyter:    

    plt.clf()
    proj = gcrs.Mollweide(central_longitude=0.0)

    fig, ax = plt.subplots(
        1,
        figsize=(16., 12.),
        dpi=100,
        frameon=False,
        subplot_kw={
            'aspect':'equal',
            'projection': proj
        },
    )

Results in an error here:

    ~/dev/ocrtest/venv/lib/python3.6/site-packages/geoplot/crs.py in _as_mpl_axes(proj)
        278 
        279     """
    --> 280     proj = proj.load(gpd.GeoDataFrame(), dict())
        281     return proj._as_mpl_axes()

    ~/dev/ocrtest/venv/lib/python3.6/site-packages/geoplot/crs.py in load(self, df, centerings)
         56 
         57     def load(self, df, centerings):
    ---> 58         return _generic_load(self, df, {'central_longitude': centerings['central_longitude']})
         59 
         60     def _as_mpl_axes(self): return _as_mpl_axes(self)

    KeyError: 'central_longitude'

I'm seeing the same KeyError with quite a few other projections, too:

- InterruptedGoodeHomolosine
- Geostationary
- Robinson
- Sinusoidal

**Comment by ResidentMario** [comment]
Will take a look, thanks. Projections need a test suite also.

**Comment by ResidentMario** [comment]
@urschrei This should now be fixed in master for all of the cases you mentioned. Sorry it took so long to get around to fixing this! I'm only now getting around to preparing another iteration of this library.

I also appreciate any further testing/feedback you can give. :) I will soliciting feedback on further directions sometime after the current release is out.

**Comment by urschrei** [comment]
Fantastic, thank you!
