### ISSUE TITLE
Suppress Matplotlib 2.0 warning

### ISSUE THREAD

**Issue by ResidentMario** [ResidentMario/geoplot#46]
cf. #45

**Comment by geodesy99** [comment]
Another warning in the tutorial ... My skill set is not sufficient to debug this. It seems it should have been generated at the previous point in the tutorial where there was a sort of bulk loading of the data for the remaining examples:
...
collisions = gpd.read_file(geoplot_data.nyc_collision_factors())
boroughs = gpd.read_file(geoplot_data.nyc_boroughs())
<snip>
la_flights = gpd.read_file(geoplot_data.la_flights())
la_flights = la_flights.assign(
    start=la_flights.geometry.map(lambda mp: mp[0]),
    end=la_flights.geometry.map(lambda mp: mp[1]))


![geoplottest_2017-10-24 14_02_00-](https://user-images.githubusercontent.com/742406/31970392-a27bd80e-b8cc-11e7-8fbb-fb1f5e0907b6.png)

**Comment by ResidentMario** [comment]
@geodesy99 That one's expected actually. `cartopy` has a built-in dataset of low-resolution world shapes of things that it will download for the first time (with this warning) the first time you try to use it. If you rerun the cell, the warning will go away.

**Comment by geodesy99** [comment]
Ahhh .... I went out to cartopy and tracked down the warning message to https://github.com/SciTools/cartopy/blob/master/lib/cartopy/io/__init__.py , and then went to NACIS's site for Natural Earth, and the URL seemed to be okay ( although if copied from their button itself it seemed odd). 

To my naive eyes it seemed like the https://github.com/SciTools/cartopy/blob/master/lib/cartopy/io/__init__.py
```
class DownloadWarning(Warning):
    """Issued when a file is being downloaded by a :class:`Downloader`."""
pass 
```

did nothing at all ( the 'pass'). And the 
```
    def _urlopen(self, url):
        """
        Return a file handle to the given HTTP resource URL.
        Caller should close the file handle when finished with it.
        """
        warnings.warn('Downloading: {}'.format(url), DownloadWarning)
return urlopen(url)
```
would _always_ produce the warning. 

 I'm sure more will be revealed as I go along. :-) Also, it probably isn't really practical to debug anything inside of a Jupyter Notebook instead of a read IDE. 

Thanks,
Michael

**Comment by ResidentMario** [comment]
This is https://github.com/matplotlib/matplotlib/issues/9024/
