### ISSUE TITLE
I try to run plotting_with_geoplot from examples on GeoPandas 0.4.0 and it gave this error:

### ISSUE THREAD

**Issue by abelguima** [ResidentMario/geoplot#71]
import geoplot

geoplot.polyplot(df, figsize=(8, 4))

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-e57730a4b3d5> in <module>()
----> 1 import geoplot
      2 
      3 geoplot.polyplot(df, figsize=(8, 4))

/usr/local/lib/python3.6/dist-packages/geoplot/__init__.py in <module>()
----> 1 from .geoplot import (pointplot, polyplot, choropleth, aggplot, cartogram, kdeplot, sankey, voronoi,
      2                       __version__)
      3 from .crs import (PlateCarree, LambertCylindrical, Mercator, Miller, Mollweide, Robinson, Sinusoidal,
      4                   InterruptedGoodeHomolosine, Geostationary, NorthPolarStereo, SouthPolarStereo, Gnomonic,
      5                   AlbersEqualArea, AzimuthalEquidistant, LambertConformal, Orthographic, Stereographic,

/usr/local/lib/python3.6/dist-packages/geoplot/geoplot.py in <module>()
     19     from geopandas.plotting import _mapclassify_choro
     20 else:
---> 21     from geopandas.plotting import __pysal_choro as _mapclassify_choro
     22 
     23 __version__ = "0.2.3"

ImportError: cannot import name '__pysal_choro'

**Comment by ResidentMario** [comment]
The `__pysal_choro` internal routine is borrowed from `geopandas` by `geoplot`. It was renamed and the logic slightly refactored to `_mapclassify_choro` on `master`. So the current state of the world is:

* `geopandas==0.4.0`, installed from `pip` &mdash; `geoplot` works, uses `__pysal_choro`
* `geopandas==0.4.0`, installed from the `master` branch on `git` (via e.g. `pip install -e .`) &mdash; `geoplot` doesn't work because `geopandas` git repo is still tagged 0.4.0 but the logic has already been updated to use `_mapclassify_choro`
* `geopandas==0.4.1`, installed from `pip` or from `git` in the future, once 0.4.1 is released &mdash; `geoplot` works, uses `_mapclassify_choro`.

I'm guessing you installed `geopandas` from the `git` repository?

As you can see, things are little awkward. @jorisvandenbossche FYI.

**Comment by abelguima** [comment]
Thanks, I'll try that!

**Comment by jorisvandenbossche** [comment]
> geopandas==0.4.0, installed from the master branch on git (via e.g. pip install -e .) — geoplot doesn't work because geopandas git repo is still tagged 0.4.0 but the logic has already been updated to use _mapclassify_choro

BTW, if you would use `LooseVersion(gpd.__version__) > LooseVersion('0.4.0')` instead of `LooseVersion(gpd.__version__) >= LooseVersion('0.4.1')`, it would already work with geopandas master as well (as master's version is something like '0.4.0+116.g85e9644', which is higher than 0.4.0.

(noted this while trying to release 0.4.1. But as long as I don't actually tag it as 0.4.1, it's not working with geoplot, making it more difficult to try out)

**Comment by jorisvandenbossche** [comment]
Also to say that I am doing a 0.4.1 release today that should resolve this.

**Comment by jorisvandenbossche** [comment]
Update: 0.4.1 release was pushed to pypi yesterday, and is also already available on conda-forge

**Comment by ResidentMario** [comment]
Should be resolved now.
